# Generated by Django 5.1.2 on 2024-11-04 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personal', '0001_initial'),
        ('Traslados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_mensualidad', models.IntegerField()),
                ('mes_mensualidad', models.CharField(max_length=20)),
                ('monto_mensualidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='Traslados.usuario')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensualidades', to='Personal.personal')),
            ],
        ),
    ]
