# Generated by Django 5.1.4 on 2025-05-21 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensualidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='año_mensualidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='monto_mensualidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
