# Generated by Django 5.1.2 on 2024-11-04 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_conductor', models.CharField(max_length=12, unique=True)),
                ('nombre_conductor', models.CharField(max_length=50)),
                ('apellido_conductor', models.CharField(max_length=50)),
                ('telefono_conductor', models.CharField(max_length=15)),
                ('genero_conductor', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('codigo_escuela', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_escuela', models.CharField(max_length=100)),
                ('ubicacion_escuela', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_usuario', models.CharField(max_length=12, unique=True)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('representante_usuario', models.CharField(max_length=50)),
                ('direccion_usuario', models.CharField(max_length=200)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='Traslados.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_vehiculo', models.CharField(max_length=10, unique=True)),
                ('marca_vehiculo', models.CharField(max_length=50)),
                ('modelo_vehiculo', models.CharField(max_length=50)),
                ('año_vehiculo', models.IntegerField()),
                ('capacidad_vehiculo', models.IntegerField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='Traslados.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='RutaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='Traslados.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='Traslados.vehiculo')),
            ],
        ),
    ]
